/**
* @file $Header: GeneralException.cpp
* 
* NAME: GeneralException
* 
* BASE CLASSES: Exception
* 
* PURPOSE: For exceptions generated by ODBC connectivity and other general exceptions.
* 
* AUTHOR: Gowri Ramasubramanian
* 
* $Revision: 1.9 $
* 
* $Log: GeneralException.cpp,v $
* Revision 1.9  2005/09/01 05:40:48  Jignesh.Kanchanlal
* Documentation modified for the Release
*
* Revision 1.8  2005/08/30 05:23:25  Jignesh.Kanchanlal
* Bugs after Testing fixed
*
* Revision 1.7  2005/08/23 11:57:15  Jignesh.Kanchanlal
* Code Review Comments Incorporated
*
* Revision 1.6  2005/08/23 04:35:17  Jignesh.Kanchanlal
* Code Review Comments Incorporated
*
* Revision 1.4  2005/08/12 12:29:56  Jignesh.Kanchanlal
* Added for the first time
*
* 
* COPYRIGHT NOTICE:
* Copyright (c) 2005 C++ Capability team at Accenture. All rights reserved.
*/


///////////////////////////////////////////////////////////////
// Includes
#include <common/GeneralException.h>
#ifdef ALOGGER
	#include <logger/Logger.h> ///<logging comments
#endif


	
	/** Overloaded default Constructor.
	* <BR>NAME: Error
	* <BR>DESCRIPTION: Constructor for the GeneralException Object.
	* <BR>SIDE EFFECTS: Nil
	* <BR>@param Nil
	*/
	GeneralException::GeneralException()
	{
		#ifdef ALOGGER
			logger::Logger::getInstance().debug(__FILE__, __LINE__, __FUNCTION__, "");
		#endif
	}

	/** Overloaded constructor.
	* <BR>NAME: GeneralException(const string)
	* <BR>DESCRIPTION: constructor for the GeneralException Object.
	* <BR>SIDE EFFECTS: Nil
	* <BR>@param Nil
	*/
	GeneralException::GeneralException(const string str)
	{
		#ifdef ALOGGER
			logger::Logger::getInstance().debug(__FILE__, __LINE__, __FUNCTION__, 
							"Overloaded constructor with string");
		#endif
		setMessage(str);
	}

	/** Default Destructor.
	* <BR>NAME: ~GeneralException
	* <BR>DESCRIPTION: Destructor for the GeneralException Object.
	* <BR>SIDE EFFECTS: Nil
	* <BR>@param Nil
	*/
	GeneralException::~GeneralException()
	{
		#ifdef ALOGGER
			logger::Logger::getInstance().debug(__FILE__, __LINE__, __FUNCTION__, "");
		#endif
	}

	/** Overloaded copy constructor.
	* <BR>NAME: GeneralException(const GeneralException &)
	* <BR>DESCRIPTION: Copy Constructor for the GeneralException Object.
	* <BR>SIDE EFFECTS: Being protected and overloaded the user cannot call this. Hence empty implementation.
	* <BR>@param Const reference to GeneralException object
	*/
	GeneralException::GeneralException(const GeneralException&)
	{
		#ifdef ALOGGER
			logger::Logger::getInstance().debug(__FILE__, __LINE__, __FUNCTION__, 
							"Copy Constructor");
		#endif
	}

	/** Overloaded assignment operator.
	* <BR>NAME: GeneralException & operator=(const GeneralException &)
	* <BR>DESCRIPTION: Assignment operator overload for the GeneralException Object.
	* <BR>SIDE EFFECTS: Being protected and overloaded the user cannot call this. Hence empty implementation.
	* <BR>@param const Reference to GeneralException object
	* <BR>RETURN: 
	* 	@return Reference to GeneralException Object
	*/
	GeneralException& GeneralException::operator =(const GeneralException&)
	{
		#ifdef ALOGGER
			logger::Logger::getInstance().debug(__FILE__, __LINE__, __FUNCTION__, 
							"Overloaded Assignment operator");
		#endif
		return *this;
	}


